sudo: false
language: python
python:
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - 'pypy'
    - 'pypy3'
install:
    - python setup.py install
    - pip install codecov
script: python setup.py test
after_script:
    - codecov
os:
    - linux
